version = 0.1

[default.deploy.parameters]
stack_name = "pr-review-agent"
resolve_s3 = true
s3_prefix = "pr-review-agent"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "WeaviateUrl=\"https://o2l0nyx9sxmea5f1bsxsu │\" SupabaseUrl=\"https://utnyzznhokznvoiwgvea.supabase.co\" LangsmithProject=\"pr-review-agent\" PromptVersion=\"v1\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
